on:
  push:
    branches:
      # - master
      - ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-verions: '12.16.x'
    - name: Check if version has been updated
      id: check
      uses: EndBug/version-check@v1

    - name: Exit on version unchanged
      if: steps.check.outputs.changed != 'true'
      run: |
        echo "No version change :/"
        exit 1

    - name: Continue on version changed
      if: steps.check.outputs.changed == 'true'
      run: |
        'echo "Version change found in commit ${{ steps.check.outputs.commit }}! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'
    - uses: mr-smithers-excellent/docker-build-push@v3
      name: Build & push Docker image
      with:
        image: dohaicuong/graphql-relay-ts
        tag: ${{ steps.check.outputs.version }}
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

